### ISSUE TITLE
如何计算权值

### ISSUE THREAD

**Issue by meishadevs** [Rain-1214/JavaScript-IDcard-Question#1]
我想问一下你这里的权值是什么意思，如何计算的

**Comment by Rain-1214** [comment]
二代身份证号码一共18位，前17位每个数值都有对应的一个权值。是固定的。具体可以移步[https://baike.baidu.com/item/%E8%BA%AB%E4%BB%BD%E8%AF%81%E6%A0%A1%E9%AA%8C%E7%A0%81/3800388?fr=aladdin](url) 
写的很清楚。

**Comment by meishadevs** [comment]
@Rain-1214 谢谢，我知道了
